#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : SDI_RX_Subsystem_v1_0_bfm_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri May 29 17:05:20 +0200 2020
# SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved. 
#
# usage: SDI_RX_Subsystem_v1_0_bfm_1.sh [-help]
# usage: SDI_RX_Subsystem_v1_0_bfm_1.sh [-lib_map_path]
# usage: SDI_RX_Subsystem_v1_0_bfm_1.sh [-noclean_files]
# usage: SDI_RX_Subsystem_v1_0_bfm_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'SDI_RX_Subsystem_v1_0_bfm_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm gtwizard_ultrascale_v1_7_2 v_smpte_uhdsdi_v1_0_5 axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_1 axi_vip_v1_1_1)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "SDI_RX_Subsystem_v1_0_bfm_1.sh - Script generated by export_simulation (Vivado v2017.4 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/tx_vio_i/sim/tx_vio_i.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work gtwizard_ultrascale_v1_7_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_bit_sync.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gthe3_cpll_cal.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gthe3_cal_freqcnt.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_reset_sync.v" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/sim/gtwizard_ultrascale_v1_7_gthe4_channel.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/sim/v_smpte_uhdsdi_gtwiz_gthe4_channel_wrapper.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/sim/v_smpte_uhdsdi_gtwiz_gtwizard_gthe4.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/sim/v_smpte_uhdsdi_gtwiz_gtwizard_top.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_gtwiz/sim/v_smpte_uhdsdi_gtwiz.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_smpte_uhdsdi_v1_0_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_rxtx/hdl/v_smpte_uhdsdi_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/src/v_smpte_uhdsdi_rxtx/sim/v_smpte_uhdsdi_rxtx.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/kugth_uhdsdi_3g_wrapper.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/kugth_uhdsdi_3g_wrapper_support.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/kugth_uhdsdi_control.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/kugth_uhdsdi_drp_control.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/kugth_uhdsdi_drp_control_fsm.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/kugth_uhdsdi_rx_control.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/kugth_uhdsdi_tx_control.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/multigenHD.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/multigenHD_horz.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/multigenHD_output.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/multigenHD_vert.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/sync_block.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/uhdsdi_rate_detect.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/uhdsdi_vidgen.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/vidgen_ntsc.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/vidgen_pal.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/hdl/SDI_RX_Subsystem_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/bs_flex_v_2.vhd" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/nidru_20_v_7.vhd" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/src/nidru_20_wrapper.vhd" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/33d1/hdl/SDI_RX_Subsystem_v1_0.vhd" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0/sim/SDI_RX_Subsystem_v1_0_bfm_1_SDI_RX_Subsystem_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_master_0_0/sim/SDI_RX_Subsystem_v1_0_bfm_1_master_0_0_pkg.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_master_0_0/sim/SDI_RX_Subsystem_v1_0_bfm_1_master_0_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../EIVE-SDI_RX_Subsystem.srcs/sources_1/bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/02c8/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ipshared/68f7/hdl/sim_clk_gen.v" \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/ip/SDI_RX_Subsystem_v1_0_bfm_1_sim_clk_gen_0_1/sim/SDI_RX_Subsystem_v1_0_bfm_1_sim_clk_gen_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/SDI_RX_Subsystem_v1_0_bfm_1/sim/SDI_RX_Subsystem_v1_0_bfm_1.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.SDI_RX_Subsystem_v1_0_bfm_1 xil_defaultlib.glbl -o SDI_RX_Subsystem_v1_0_bfm_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./SDI_RX_Subsystem_v1_0_bfm_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./SDI_RX_Subsystem_v1_0_bfm_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key SDI_RX_Subsystem_v1_0_bfm_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc SDI_RX_Subsystem_v1_0_bfm_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./SDI_RX_Subsystem_v1_0_bfm_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: SDI_RX_Subsystem_v1_0_bfm_1.sh [-help]\n\
Usage: SDI_RX_Subsystem_v1_0_bfm_1.sh [-lib_map_path]\n\
Usage: SDI_RX_Subsystem_v1_0_bfm_1.sh [-reset_run]\n\
Usage: SDI_RX_Subsystem_v1_0_bfm_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
